vote:

        build: ./vote

        command: python app.py

        volumes:

            - ./vote:/app

        ports:

            - "5000:80"

        networks:

            - front-tier

            - back-tier